/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

// System Control Unit (SCU) registers
#define SCU_BASE_ADDRESS        (0xF0036000)
#define SCU_WDTCPU0CON0         (*(volatile unsigned int *)(SCU_BASE_ADDRESS + 0x100))

#define LCK                     1
#define ENDINIT                 0

// Generic Timer Module (GTM) registers
#define GTM_BASE_ADDRESS        (0xF0100000)
#define GTM_CLC                 (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x9FD00))
#define GTM_TOUTSEL6            (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x9FD48))

#define DISS                    1
#define DISR                    0
#define SEL7                    14

// Generic Timer Module (GTM) - Clock Management Unit (CMU) registers
#define GTM_CMU_CLK_EN          (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x00300))
#define GTM_CMU_FXCLK_CTRL      (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x00344))

#define EN_FXCLK                22
#define FXCLK_SEL               0

// Generic Timer Module (GTM) - Timer Output Module (TOM) registers - TOM0, Channel 1 - Led PWM
#define GTM_TOM0_TGC0_GLB_CTRL      (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08030))
#define GTM_TOM0_TGC0_ENDIS_CTRL    (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08070))
#define GTM_TOM0_TGC0_OUTEN_CTRL    (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08078))
#define GTM_TOM0_TGC0_FUPD_CTRL     (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08038))

#define GTM_TOM0_CH1_CTRL           (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08040))
#define GTM_TOM0_CH1_SR0            (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08044))
#define GTM_TOM0_CH1_SR1            (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08048))

#define UPEN_CTRL1              18
#define ENDIS_CTRL1             2
#define OUTEN_CTRL1             2
#define FUPD_CTRL1              2
#define RSTCN0_CH1              18


// Generic Timer Module (GTM) - Timer Output Module (TOM) registers - TOM0, Channel 11 - buzzer PWM
// 0~7 / 8~14 / 15
#define GTM_TOM0_TGC1_GLB_CTRL      (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08230))
#define GTM_TOM0_TGC1_ENDIS_CTRL    (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08270))
#define GTM_TOM0_TGC1_OUTEN_CTRL    (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08278))
#define GTM_TOM0_TGC1_FUPD_CTRL     (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08238))

// TOM0 Channel 11 레지스터 주소 (0x08000 + 11 * 0x40 = 0x082C0)
#define GTM_TOM0_CH11_CTRL          (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x082C0))
#define GTM_TOM0_CH11_SR0           (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x082C4))
#define GTM_TOM0_CH11_SR1           (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x082C8))

// TGC1(8~15) 그룹 내에서 CH11의 인덱스는 3 (8=0, 9=1, 10=2, 11=3)
// 각 비트 필드 위치 계산: 하위 제어는 index*2, 상위 제어는 16 + index*2
#define UPEN_CTRL11                 22  // 16 + (3 * 2)
#define ENDIS_CTRL11                6   // (3 * 2)
#define OUTEN_CTRL11                6   // (3 * 2)
#define FUPD_CTRL11                 6   // (3 * 2)
#define RSTCN0_CH11                 22  // 16 + (3 * 2)

// gtm common
#define HOST_TRIG               0
#define CLK_SRC_SR              12
#define SL                      11

// Port10 Base Address - for LED
#define PORT10_BASE_ADDRESS     (0xF003B000)
#define PORT10_IOCR0            (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x10))
#define PC1                     11

// Port 2 Base Address - for BUZZER
#define PORT2_BASE_ADDRESS      (0XF003A200)
#define PORT2_IOCR0             (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x10))
#define PORT2_INPUT             (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x24))
#define PORT2_OUTPUT            (*(volatile unsigned int *)(PORT2_BASE_ADDRESS))
#define PC3                     27
#define P3                      3

// timer
#define STM0_BASE_ADDRESS       (0xF0000000)
#define STM0_TIM0               (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x10))
#define STM0_CMP0               (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x30))
#define STM0_CMCON              (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x38))
#define STM0_ICR                (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x3C))
#define STM0_ISCR               (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x40))

#define CMP0EN                  (0)
#define CMP0OS                  (2)
#define CMP0IRR                 (0)
#define MSIZE0                  (0)
#define MSTART0                 (8)

#define SRC_BASE_ADDRESS        (0xF0038000)
#define SRC_STM0_SR0            (*(volatile unsigned int *)(SRC_BASE_ADDRESS + 0x490))

#define SRE                     (10)
#define TOS                     (11)
#define SRPN                    (0)

#define STM_FREQENCY_HZ         (100000000UL)
#define STM0_TICKS_1SEC         (STM_FREQENCY_HZ)
#define STM0_TICKS_HALF_SEC     (STM_FREQENCY_HZ / 2)
#define STM0_TICKS_10MS         (STM_FREQENCY_HZ / 100)

#define STM0_ISR_PRIORITY       (10)

volatile unsigned int g_stm0_sec_count = 0;

void init_LED(void);
void init_Buzzer(void);
void init_GTM_TOM0_PWM(void);
void Init_Timer_1sec_Interrupt(void);

IfxCpu_syncEvent cpuSyncEvent = 0;

int g_isOver = 0;

__interrupt(STM0_ISR_PRIORITY)      __vector_table(0)
void Stm0_Compare0_Isr(void) {

    STM0_ISCR |= ((0x1) << CMP0IRR);                // clear compare 0 interrupt request flag

    // STM0_CMP0 += (unsigned int)STM0_TICKS_1SEC;     // set compare 0 to trigger next interrupt after 1 second
    // STM0_CMP0 += (unsigned int)STM0_TICKS_HALF_SEC;  // set compare 0 to trigger next interrupt after 0.5 second
    STM0_CMP0 += (unsigned int)STM0_TICKS_10MS;  // set compare 0 to trigger next interrupt after 10 ms

    g_stm0_sec_count++;                         // increment the seconds counter

    // LED 밝기가 밝아졌다가 최대이후 다시 어두워지게
    if (GTM_TOM0_CH1_SR1 >= GTM_TOM0_CH1_SR0) {
        g_isOver = 1;
    } else if (GTM_TOM0_CH1_SR1 <= 0) {
        g_isOver = 0;
    }

    if (g_isOver == 0) {
        GTM_TOM0_CH1_SR1 += 125; // 밝기 증가
        // 🔥 추가: 부저 음정 높이기 (주기를 짧게)
        // 너무 주기가 짧아지는 것을 막기 위해 하한선 설정
        if(GTM_TOM0_CH11_SR0 > 2000) GTM_TOM0_CH11_SR0 -= 50;

    } else {
        GTM_TOM0_CH1_SR1 -= 125; // 밝기 감소
        // 🔥 추가: 부저 음정 낮추기 (주기를 길게)
        if(GTM_TOM0_CH11_SR0 < 8000) GTM_TOM0_CH11_SR0 += 50;
    }

    // 부저의 볼륨(듀티비)은 항상 현재 주기(SR0)의 절반(50%)을 유지
    GTM_TOM0_CH11_SR1 = GTM_TOM0_CH11_SR0 / 2;
}

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);
    
    Init_Timer_1sec_Interrupt();
    init_LED();
    init_Buzzer();
    init_GTM_TOM0_PWM();

    while(1)
    {
    }

    return (1);
}

void init_LED(void) {
    PORT10_IOCR0 &= ~((0x1F) << PC1);   // reset pc1 in port 10 IOCR0 register
    PORT10_IOCR0 |= ((0x11) << PC1);    // set pc1 to push-pull mode in port10 IOCR register
}

void init_Buzzer(void) {
    PORT2_IOCR0 &= ~((0x1F) << PC3);    // reset pc3 in port 2 IOCR0 register
    PORT2_IOCR0 |= ((0x11) << PC3);     // set pc3 to alt. function 1 mode in port2 IOCR register
}

void init_GTM_TOM0_PWM(void) {
    // Password Access to unlock CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 = ((SCU_WDTCPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);    // clear LCK bit and set ENDINIT bit
    while ((SCU_WDTCPU0CON0 & (1 << LCK)) != 0);    // wait until to unlock CPU0 WDT Control Register 0
    
    // Modify Access to clear the ENDINIT bit in CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 = ((SCU_WDTCPU0CON0 ^ 0xFC) | (1 << LCK)) & ~(1 << ENDINIT);        // set LCK bit and clear ENDINIT bit
    while ((SCU_WDTCPU0CON0 & (1 << LCK)) == 0);    // wait until to clear the ENDINIT bit in CPU0 WDT Control Register 0

    // Enable GTM module
    GTM_CLC &= ~(1 << DISR);                        // clear DISS bit to enable GTM module

    // Password Access to unlock CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 = ((SCU_WDTCPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);    // clear LCK bit and set ENDINIT bit
    while ((SCU_WDTCPU0CON0 & (1 << LCK)) != 0);    // wait until to unlock CPU0 WDT Control Register 0

    // Modify Access to set the ENDINIT bit in CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 = ((SCU_WDTCPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);     // set LCK bit and set ENDINIT bit
    while ((SCU_WDTCPU0CON0 & (1 << LCK)) == 0);    // wait until to set the ENDINIT bit in CPU0 WDT Control Register 0

    while ((GTM_CLC & (1 << DISS)) != 0);           // wait until GTM module is enabled

    // GTM Fixed Clock (FXCLK) Configuration
    GTM_CMU_FXCLK_CTRL &= ~((0xF) << FXCLK_SEL);    // Input clock of CMU_FXCLK     // clear FXCLK_SEL bits to select FXCLK source as PLL1
    GTM_CMU_CLK_EN |= ((0x2) << EN_FXCLK);          // Enable all CMU_FXCLK         // set EN_FXCLK bit to enable FXCLK


    /////////////////////////////////////////////////////////////// LED PWM - TOM_CH1 Configuration
    // Allow Shadow register update 
    GTM_TOM0_TGC0_GLB_CTRL |= ((0x2) << UPEN_CTRL1);    // Enable update of TOM0 channel 1 shadow register

    GTM_TOM0_TGC0_FUPD_CTRL |= ((0x2) << FUPD_CTRL1);    // Enable force update of TOM0 channel 1
    GTM_TOM0_TGC0_FUPD_CTRL |= ((0x2) << RSTCN0_CH1);    // Reset CN0 of TOM0 channel 1 on force update

    /*
     * TOM0 CH2 비활성화 후 설정
     * ENDIS_CTRL2 = 1 : channel disable request
     * OUTEN_CTRL2 = 1 : channel output disable request
     */

    GTM_TOM0_TGC0_ENDIS_CTRL |= ((0x2) << ENDIS_CTRL1);    // Disable TOM0 channel 1
    GTM_TOM0_TGC0_OUTEN_CTRL |= ((0x2) << OUTEN_CTRL1);    // Disable TOM0 channel 1 output


    /*
     * TOM0 CH1 Control 설정
     * 
     * CLK_SRC_SR   = 0 : FXCLK0 사용
     * SL           = 1 : PWM active level high, Shadow register 사용
     */

    GTM_TOM0_CH1_CTRL |= (1 << SL);                 // High signal level for duty cycle // set SL bit to select PWM active level high and use shadow register

    GTM_TOM0_CH1_CTRL &= ~((0x7) << CLK_SRC_SR);    // Clock source : CMU_FXCLK(1) = 6250 kHz // clear CLK_SRC_SR bits to select FXCLK0 as clock source
    GTM_TOM0_CH1_CTRL |= ((0x1) << CLK_SRC_SR);     // Clock source : CMU_FXCLK(1) = 6250 kHz // set CLK_SRC_SR bits to select FXCLK0 as clock source

    /*
     * PWM 주기 및 듀티비 설정
     * CM0 = PWM period
     * CM1 = PWM duty cycle // high 구간 길이
     */
    GTM_TOM0_CH1_SR0 = 12500;                        // PWM freq. = 6250 kHz / 12500 = 500Hz
    // GTM_TOM0_CH1_SR1 = 6250;                         // PWM duty cycle = 50% (high 구간 길이)
    GTM_TOM0_CH1_SR1 = 12500;                         // PWM duty cycle = 25% (high 구간 길이)

    GTM_TOUTSEL6 &= ~((0x3) << SEL7);                    // Select TOM0_CH1 as output source for TOUT6 // clear SEL7 bits to select TOM0_CH1 as output source for TOUT6

    /////////////////////////////////////////////////////////// Buzzer PWM
    // Shadow register 및 Force Update 허용
    GTM_TOM0_TGC1_GLB_CTRL |= ((0x2) << UPEN_CTRL11);   
    GTM_TOM0_TGC1_FUPD_CTRL |= ((0x2) << FUPD_CTRL11);   
    GTM_TOM0_TGC1_FUPD_CTRL |= ((0x2) << RSTCN0_CH11);   

    // CH11 활성화 및 출력 활성화 (0x2 = Enable)
    GTM_TOM0_TGC1_ENDIS_CTRL &= ~((0x3) << ENDIS_CTRL11);
    GTM_TOM0_TGC1_ENDIS_CTRL |= ((0x2) << ENDIS_CTRL11); 
    GTM_TOM0_TGC1_OUTEN_CTRL &= ~((0x3) << OUTEN_CTRL11);
    GTM_TOM0_TGC1_OUTEN_CTRL |= ((0x2) << OUTEN_CTRL11); 

    // CH11 Control 설정 (Active High, FXCLK0 사용)
    GTM_TOM0_CH11_CTRL |= (1 << SL);                 
    GTM_TOM0_CH11_CTRL &= ~((0x7) << CLK_SRC_SR);    
    GTM_TOM0_CH11_CTRL |= ((0x1) << CLK_SRC_SR);     

    // 부저 PWM 주기(음정) 및 듀티비(볼륨) 초기 설정 (약 1kHz)
    GTM_TOM0_CH11_SR0 = 6250;                        
    GTM_TOM0_CH11_SR1 = 3125;

    //////////////////// set HOST_TRIG bit to trigger shadow register update for TOM0 channel 1
    // Host trigger shadow register update
    GTM_TOM0_TGC0_GLB_CTRL |= ((0x1) << HOST_TRIG);    // Trigger shadow register update for TOM0 channel 1
    // GTM_TOM0_TGC1_GLB_CTRL |= ((0x1) << HOST_TRIG);
}

void Init_Timer_1sec_Interrupt(void) {
    unsigned int currentTime;

    STM0_ICR &= ~((0x1) << CMP0EN);                 // disable compare 0 interrupt

    SRC_STM0_SR0 &= ~((0x1) << SRE);                // disable service request generation

    STM0_CMCON &= ~((0x1) << MSTART0);              // set compare 0 to start counting from STM0_TIM0
    STM0_CMCON |= ((0x1F) << MSIZE0);               // set compare 0 to 32-bit mode

    STM0_ICR &= ~((0x1) << CMP0OS);                 // set compare 0 to one-shot mode

    STM0_ISCR |= ((0x1) << CMP0IRR);                // clear compare 0 interrupt request flag

    currentTime = STM0_TIM0;                        // get current STM0 time

    // STM0_CMP0 = currentTime + (unsigned int)STM0_TICKS_1SEC;
    // STM0_CMP0 = currentTime + (unsigned int)STM0_TICKS_HALF_SEC;
    STM0_CMP0 = currentTime + (unsigned int)STM0_TICKS_10MS;

    SRC_STM0_SR0 &= ~(STM0_ISR_PRIORITY << SRPN);   // clear service request priority field
    SRC_STM0_SR0 |= (STM0_ISR_PRIORITY << SRPN);    // set service request priority to 

    SRC_STM0_SR0 &= ~(0x3 << TOS);                  // route service request to CPU0 
    SRC_STM0_SR0 |= ((0x1) << SRE);                 // enable service request generation

    STM0_ICR |= ((0x1) << CMP0EN);                  // enable compare 0 interrupt
}