/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#define PORT10_BASE_ADDRESS     (0xF003B000)
#define PORT10_IOCR0            (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x10))
#define PORT10_OUTPUT           (*(volatile unsigned int *)(PORT10_BASE_ADDRESS))
#define PORT10_OMR              (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x4))

#define PC1     11
#define PC2     19

#define PS1     1
#define PS2     2

#define PCL1    17
#define PCL2    18

#define P1      1
#define P2      2

IfxCpu_syncEvent cpuSyncEvent = 0;

void init_LED(void) {
    // reset PC1 in port 10 iocr0 register
    PORT10_IOCR0 &= ~((0x1F) << PC1);       // red
    PORT10_IOCR0 &= ~((0x1F) << PC2);       // blue



    // set pc1 to push-pull mode in port 10 iocr0 register
    PORT10_IOCR0 |= ((0x10) << PC1);        // red
    PORT10_IOCR0 |= ((0x10) << PC2);        // blue
}

void blink_LED(void) {
//    static int LED_flag = 1;
//
//    if (LED_flag == 1) {
////        PORT10_OUTPUT |= 0x1 << P1;   // red
//        PORT10_OUTPUT |= 0x3 << P2;     // blue
//        LED_flag = 0;
//    }
//    else {
////        PORT10_OUTPUT &= 0x0 << P1;   // red
//        PORT10_OUTPUT &= 0x0 << P2;     // blue
//        LED_flag = 1;
//    }

///////////////////////////
    // set 1 to pcl1 and ps1 in port 10 output modification register for led toggle
//    PORT10_OMR |= ((0x1 << PCL1) | (0x1 << PS1));   // red
//    PORT10_OMR |= ((0x1 << PCL2) | (0x1 << PS2));   // blue

///////////////////////////
// eg3
        PORT10_OMR |= ((0x1 << PCL1) | (0x0 << PS1));   // red
        PORT10_OMR |= ((0x1 << PCL2) | (0x0 << PS2));   // blue
        // all off
        // todo: delay
        for (int cycle = 0; cycle < 20000000; cycle++) ;

        PORT10_OMR |= ((0x0 << PCL1) | (0x1 << PS1));   // red
//        PORT10_OMR |= ((0x1 << PCL2) | (0x0 << PS2));   // blue
        // red on, blue off
        // todo: delay
        for (int cycle = 0; cycle < 20000000; cycle++) ;

        PORT10_OMR |= ((0x1 << PCL1) | (0x0 << PS1));   // red
        PORT10_OMR |= ((0x0 << PCL2) | (0x1 << PS2));   // blue
        // red off, blue on
        // todo: delay
        for (int cycle = 0; cycle < 20000000; cycle++) ;

        PORT10_OMR |= ((0x0 << PCL1) | (0x1 << PS1));   // red
//        PORT10_OMR |= ((0x0 << PCL2) | (0x1 << PS2));   // blue
        // red on, blue on
        // todo: delay
        for (int cycle = 0; cycle < 20000000; cycle++) ;


}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    init_LED();
        
    while(1)
    {
        blink_LED();
//        for (int cycle = 0; cycle < 20000000; cycle++) ;
    }
}
