/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#define PORT2_BASE_ADDRESS      (0XF003A200)
#define PORT2_IOCR0             (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x10))
#define PORT2_INPUT             (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x24))

#define PORT10_BASE_ADDRESS     (0xF003B000)
#define PORT10_IOCR0            (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x10))
#define PORT10_OUTPUT           (*(volatile unsigned int *)(PORT10_BASE_ADDRESS))
#define PORT10_OMR              (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x4))

#define PC1                     11
#define PS1                     1
#define PCL1                    17

#define SCU_BASE_ADDRESS        (0xF0036000)
#define SCU_EICR1               (*(volatile unsigned int *)(SCU_BASE_ADDRESS + 0x214))
#define SCU_IGCR0               (*(volatile unsigned int *)(SCU_BASE_ADDRESS + 0x22C))

#define EXIS0                   4
#define FEN0                    8
#define EIEN0                   11
#define INP0                    12
#define IGP0                    14

#define SRC_BASE_ADDRESS        (0xF0038000)
#define SRC_SCU_ERU0            (*(volatile unsigned int *)(SRC_BASE_ADDRESS + 0xCD4))

// SRC related
#define SRE                     10
#define TOS                     11

IfxCpu_syncEvent cpuSyncEvent = 0;


__interrupt(0x0F)   __vector_table(0)
void ISR0(void) {
    PORT10_OMR |= ((0x1 << PCL1) | (0x1 << PS1));
}

void init_LED(void) {
    // reset pc1 in port 10 IOCR0 register
    PORT10_IOCR0 &= ~((0x1F) << PC1);

    // set pc1 to push-pull mode in port10 IOCR reg
    PORT10_IOCR0 |= ((0x10) << PC1);
}

void init_switch(void) {
    // reset pc1 in port 2 IOCR0 register
    PORT2_IOCR0 &= ~((0x1F) << PC1);

    // set pc1 to push-pull mode in port2 IOCR reg
    PORT2_IOCR0 |= ((0x02) << PC1);
}

void init_ERU(void) {
    //ERU; External Request Unit  setting
    SCU_EICR1 &= ~(0x7 << EXIS0);           // clear input source selection field
    SCU_EICR1 |= (0x1 << EXIS0);            // select P02.1 as ERU input source

    SCU_EICR1 |= (0x1 << FEN0);             // Enable falling-edge detection
    SCU_EICR1 |= (0x1 << EIEN0);            // Endable event generation for input channel

    SCU_EICR1 &= ~(0x7 << INP0);            // route event to output channel 0

    SCU_IGCR0 &= ~(0x3 << IGP0);            // clear gating config for output channel 0
    SCU_IGCR0 |= (0x1 << IGP0);             // activate interrupt ouput when trigger occurs


    // SRC; Service Request Control setting
    SRC_SCU_ERU0 &= ~(0xFF);                // clear service request prioirty field
    SRC_SCU_ERU0 |= (0xF);                  // set interrupr priority to 0x10(?)

    SRC_SCU_ERU0 |= (1 << SRE);             // enable service request generation
    SRC_SCU_ERU0 &= ~(0x3 << TOS);          // route service request to CPU0
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    init_LED();
    init_switch();
    init_ERU();
        
    while(1)
    {
    }
}
