/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#define PORT2_BASE_ADDRESS      (0XF003A200)
#define PORT2_IOCR4             (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x14))
#define PORT2_OUTPUT            (*(volatile unsigned int *)(PORT2_BASE_ADDRESS))
#define PORT2_OMR               (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x4))

#define PORT10_BASE_ADDRESS     (0xF003B000)
#define PORT10_IOCR0            (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x10))
#define PORT10_IOCR4            (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x14))
#define PORT10_OUTPUT           (*(volatile unsigned int *)(PORT10_BASE_ADDRESS))
#define PORT10_OMR              (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x4))

#define PC3     27
#define PC5     11
#define PC7     27

#define P3      3
#define P5      5
#define P7      7

#define PS3     3
#define PS5     5
#define PS7     7

#define PCL3    19
#define PCL5    21
#define PCL7    23

IfxCpu_syncEvent cpuSyncEvent = 0;

void init_RGBLED(void) {
    PORT2_IOCR4 &= ~((0x1F) << PC7);    // reset pc7 in port2 iocr4 reg
    PORT2_IOCR4 |= ((0x10) << PC7);     // set pc7 to push-pull mod in port2 iocr4 reg

    PORT10_IOCR4 &= ~((0x1F) << PC5);   // reset pc5 in port10 iocr4 reg
    PORT10_IOCR4 |= ((0x10) << PC5);    // set pc5 to push-pull mod in port10 iocr4 reg

    PORT10_IOCR0 &= ~((0x1F) << PC3);   // reset pc5 in port10 iocr4 reg
    PORT10_IOCR0 |= ((0x10) << PC3);    // set pc3 to push-pull mod in port10 iocr0 reg
}

void blink_RGBLED(void) {
//    static int LED_flag = 1;
//
//    if (LED_flag == 1) {
//        PORT10_OUTPUT |= 0x1 << P3;     // set 1 to p3 in port10 output reg for blue led on
//        PORT10_OUTPUT |= 0x1 << P5;     // set 1 to p5 in port10 output reg for green led on
//        PORT2_OUTPUT |= 0x1 << P7;      // set 1 to p7 in port2 output reg for red led on
//
//        LED_flag = 0;
//    }
//    else {
//        // set 0 to pN in portN output reg for led off
//        PORT10_OUTPUT &= 0x0 << P3;
//        PORT10_OUTPUT &= 0x0 << P5;
//        PORT2_OUTPUT &= 0x0 << P7;
//
//        LED_flag = 1;
//    }

//////////
    // omr
    PORT10_OMR |= ((0x1 << PCL3) | (0x1 << PS3));   // blue toggle
    PORT10_OMR |= ((0x1 << PCL5) | (0x1 << PS5));   // green toggle
    PORT2_OMR |= ((0x1 << PCL7) | (0x1 << PS7));    // red toggle
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    init_RGBLED();
        
    while(1)
    {
        blink_RGBLED();

        for(int cycle = 0; cycle < 20000000; cycle++)
            ;
    }
}
