/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxStm_reg.h"
#include "IfxSrc_reg.h"
#include "IfxCpu_Irq.h"

#define PORT10_BASE_ADDRESS     (0xF003B000)
#define PORT10_IOCR0            (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x10))
#define PORT10_OUTPUT           (*(volatile unsigned int *)(PORT10_BASE_ADDRESS))
#define PORT10_OMR              (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x4))

#define PC1                     11
#define PS1                     1
#define PCL1                    17

#define PC2                     19
#define PS2                     2
#define PCL2                    18

#define STM0_BASE_ADDRESS       (0xF0000000)
#define STM0_TIM0               (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x10))
#define STM0_CMP0               (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x30))
#define STM0_CMCON               (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x38))
#define STM0_ICR                (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x3C))
#define STM0_ISCR               (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x40))

#define CMP0EN                  (0)
#define CMP0OS                  (2)
#define CMP0IRR                 (0)
#define MSIZE0                  (0)
#define MSTART0                 (8)

#define SRC_BASE_ADDRESS        (0xF0038000)
#define SRC_STM0_SR0            (*(volatile unsigned int *)(SRC_BASE_ADDRESS + 0x490))

#define SRE                     (10)
#define TOS                     (11)
#define SRPN                    (0)

#define STM_FREQENCY_HZ         (100000000UL)
#define STM0_TICKS_1SEC         (STM_FREQENCY_HZ)
#define STM0_TICKS_HALF_SEC     (STM_FREQENCY_HZ / 2)
#define STM0_ISR_PRIORITY       (10)

volatile unsigned int g_stm0_sec_count = 0;

IfxCpu_syncEvent cpuSyncEvent = 0;

__interrupt(STM0_ISR_PRIORITY)      __vector_table(0)
void Stm0_Compare0_Isr(void) {
    STM0_ISCR |= ((0x1) << CMP0IRR);                // clear compare 0 interrupt request flag

    // STM0_CMP0 += (unsigned int)STM0_TICKS_1SEC;     // set compare 0 to trigger next interrupt after 1 second
    STM0_CMP0 += (unsigned int)STM0_TICKS_HALF_SEC;  // set compare 0 to trigger next interrupt after 0.5 second
    
    g_stm0_sec_count++;                             // increment the seconds counter
    // PORT10_OMR |= ((0x1 << PCL1) | (0x1 << PS1));   // toggle the LED connected to P10.1

    unsigned int idx = g_stm0_sec_count % 6;        // Calculate the index based on the count

    switch (idx) {
        case 0:
            PORT10_OMR |= ((0x1 << PCL1) | (0x0 << PS1));   // red off
            PORT10_OMR |= ((0x1 << PCL2) | (0x0 << PS2));   // blue off
            break;
        
        case 1:
            PORT10_OMR |= ((0x0 << PCL1) | (0x1 << PS1));   // red on
            PORT10_OMR |= ((0x1 << PCL2) | (0x0 << PS2));   // blue off
            break;

        case 2:
            PORT10_OMR |= ((0x1 << PCL1) | (0x0 << PS1));   // red off
            PORT10_OMR |= ((0x0 << PCL2) | (0x1 << PS2));   // blue on
            break;

        case 3:
            PORT10_OMR |= ((0x0 << PCL1) | (0x1 << PS1));   // red on
            PORT10_OMR |= ((0x0 << PCL2) | (0x1 << PS2));   // blue on
            break;

        case 4:
            PORT10_OMR |= ((0x1 << PCL1) | (0x0 << PS1));   // red off
            PORT10_OMR |= ((0x0 << PCL2) | (0x1 << PS2));   // blue on
            break;

        case 5:
            PORT10_OMR |= ((0x0 << PCL1) | (0x1 << PS1));   // red on
            PORT10_OMR |= ((0x1 << PCL2) | (0x0 << PS2));   // blue off
            break;
    }
}

void Init_Timer_1sec_Interrupt(void) {
    unsigned int currentTime;

    STM0_ICR &= ~((0x1) << CMP0EN);                 // disable compare 0 interrupt

    SRC_STM0_SR0 &= ~((0x1) << SRE);                // disable service request generation

    STM0_CMCON &= ~((0x1) << MSTART0);              // set compare 0 to start counting from STM0_TIM0
    STM0_CMCON |= ((0x1F) << MSIZE0);               // set compare 0 to 32-bit mode

    STM0_ICR &= ~((0x1) << CMP0OS);                 // set compare 0 to one-shot mode

    STM0_ISCR |= ((0x1) << CMP0IRR);                // clear compare 0 interrupt request flag

    currentTime = STM0_TIM0;                        // get current STM0 time

    // STM0_CMP0 = currentTime + (unsigned int)STM0_TICKS_1SEC;
    STM0_CMP0 = currentTime + (unsigned int)STM0_TICKS_HALF_SEC;

    SRC_STM0_SR0 &= ~(STM0_ISR_PRIORITY << SRPN);   // clear service request priority field
    SRC_STM0_SR0 |= (STM0_ISR_PRIORITY << SRPN);    // set service request priority to 

    SRC_STM0_SR0 &= ~(0x3 << TOS);                  // route service request to CPU0 
    SRC_STM0_SR0 |= ((0x1) << SRE);                 // enable service request generation

    STM0_ICR |= ((0x1) << CMP0EN);                  // enable compare 0 interrupt
}

void init_LED(void) {
    // red
    PORT10_IOCR0 &= ~((0x1F) << PC1);   // reset pc1 in port 10 IOCR0 register
    PORT10_IOCR0 |= ((0x10) << PC1);    // set pc1 to push-pull mode in port10 IOCR register

    // blue
    PORT10_IOCR0 &= ~((0x1F) << PC2);   // reset pc2 in port 10 IOCR0 register
    PORT10_IOCR0 |= ((0x10) << PC2);    // set pc2 to push-pull mode in port10 IOCR register
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    Init_Timer_1sec_Interrupt();

    init_LED();
        
    while(1)
    {
    }
}
