/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#define PORT2_BASE_ADDRESS      (0XF003A200)
#define PORT2_IOCR0             (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x10))
#define PORT2_INPUT             (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x24))

#define PORT10_BASE_ADDRESS     (0xF003B000)
#define PORT10_IOCR0            (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x10))
#define PORT10_OUTPUT           (*(volatile unsigned int *)(PORT10_BASE_ADDRESS))

#define PC0                     3
#define PC1                     11
#define P1                      1

IfxCpu_syncEvent cpuSyncEvent = 0;

void off_LED(void) {
    PORT10_OUTPUT &= (0x0 << P1);
}

void on_LED(void) {
    PORT10_OUTPUT |= (0x1 << P1);
}

void init_LED(void) {
    PORT10_IOCR0 &= ~((0x1F) << PC1);   // reset pc1 in port10 iocr0 reg

    PORT10_IOCR0 |= ((0x10) << PC1);    // set pc1 to push-pull mod in port10 iocr0 reg
}

void init_switch(void) {
//    PORT2_IOCR0 &= ~((0x1F) << PC0);    // reset pc0 in port2 iocr0 reg
//
//    PORT2_IOCR0 |= ((0x02) << PC0);     // set pc0 to push-pull mod in port2 iocr0 reg

    PORT2_IOCR0 &= ~((0x1F) << PC1);    // reset pc0 in port2 iocr0 reg

    PORT2_IOCR0 |= ((0x02) << PC1);     // set pc0 to push-pull mod in port2 iocr0 reg
}

unsigned int read_switch(void) {
    // set 1 to PLC1 and PS1 in port10 output modification reg for led toggle
    return (PORT2_INPUT & 0x1);
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    init_LED();
    init_switch();
        
    while(1)
    {
        if (read_switch() == 1)
            off_LED();
        else
            on_LED();
    
        for(int cycle = 0; cycle < 20000000; cycle++)
            ;
    }
}
