/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*

기능 A — 방향 지시등(Turn signals) 구현
* 핸들 : Potentiometer                  -- o
* 좌측 깜박이: Blue LED                 -- o
* 오른쪽 깜박이: Red LED                -- o
* 왼쪽 방향 레버: SW1 버튼              -- o
* 오른쪽 방향 레버: SW2 버튼            -- o
* 방향 지시 음향 : Buzzer               -- x

* 왼쪽 방향 레버를 누르면 좌측 깜박이가 깜빡이고, Potentiometer로 왼쪽으로 돌렸다가 중앙으로 오면 좌측 깜박이가 커짐
* 오른쪽 방향 레버를 누르면 우측 깜박이가 깜빡이고, Potentiometer로 오른쪽으로 돌렸다가 중앙으로 오면 우측 깜박이가 꺼짐
* 핸들을 반대 방향으로 돌리면 경고음이 울림

---

기능 B — 오토라이트 기능 구현
* 헤드 램프 : RGB LED

* 조도 센서를 이용하여 일정한 밝기 미만이면 자동으로 헤드 램프가켜짐
* ADC를 이용한 조도 센서 제어 기능 개발 필요
* 조도 센서는 channel 6번을 사용함
* 일정한 밝기 이상이면 자동으로 헤드 램프가 꺼짐

* 앞의 기능A와 기능B를 동시에 지원해야 함

*/


#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "stdbool.h"

/* ============================================================
 * RGB / LED / Switch Registers
 * ============================================================ */
#define PORT2_BASE_ADDRESS          (0xF003A200)
#define PORT2_IOCR0                 (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x10))
#define PORT2_IOCR4                 (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x14))
#define PORT2_INPUT                 (*(volatile unsigned int *)(PORT2_BASE_ADDRESS + 0x24))
#define PORT2_OUTPUT                (*(volatile unsigned int *)(PORT2_BASE_ADDRESS))


#define PORT10_BASE_ADDRESS         (0xF003B000)
#define PORT10_IOCR0                (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x10))
#define PORT10_IOCR4                (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x14))
#define PORT10_OUTPUT               (*(volatile unsigned int *)(PORT10_BASE_ADDRESS))
#define PORT10_OMR                  (*(volatile unsigned int *)(PORT10_BASE_ADDRESS + 0x4))

#define PC0                         3
#define PC1                         11
#define PC2                         19
#define PC3                         27
#define PC5                         11
#define PC7                         27

#define P1                          1
#define P2                          2
#define P3                          3
#define P5                          5
#define P7                          7

#define PS1                         1
#define PS2                         2

#define PCL1                        17
#define PCL2                        18


/* ============================================================
 * Versatile Analog-to-Digital Converter Registers
 * ============================================================ */
#define VADC_BASE_ADDRESS           (0xF0020000)

#define VADC_CLC                    (*(volatile unsigned int *)(VADC_BASE_ADDRESS + 0x000))
#define VADC_GLOBCFG                (*(volatile unsigned int *)(VADC_BASE_ADDRESS + 0x080))
#define VADC_G4ARBCFG               (*(volatile unsigned int *)(VADC_BASE_ADDRESS + 0x1480))
#define VADC_G4ARBPR                (*(volatile unsigned int *)(VADC_BASE_ADDRESS + 0x1484))
#define VADC_G4ICLASS0              (*(volatile unsigned int *)(VADC_BASE_ADDRESS + 0x14A0))
#define VADC_G4QMR0                 (*(volatile unsigned int *)(VADC_BASE_ADDRESS + 0x1504))
#define VADC_G4QINR0                (*(volatile unsigned int *)(VADC_BASE_ADDRESS + 0x1510))
#define VADC_G4CHCTR7               (*(volatile unsigned int *)(VADC_BASE_ADDRESS + 0x161C))
#define VADC_G4RES1                 (*(volatile unsigned int *)(VADC_BASE_ADDRESS + 0x1704))

/* Field bit positions of VADC Registers */
#define DISS                        1
#define DISR                        0

#define ANONC                       0
#define ASEN0                       24
#define CSM0                        3
#define PRIO0                       0

#define CMS                         8
#define STCS                        0

#define FLUSH                       10
#define TREV                        9
#define ENGT                        0
#define RF                          5
#define REQCHNR                     0

#define RESPOS                      21
#define RESREG                      16
#define ICLSEL                      0

#define VF                          31
#define RESULT                      0


/* ============================================================
 * System Control Unit Registers
 * ============================================================ */
#define SCU_BASE_ADDRESS            (0xF0036000)
#define SCU_WDTCPU0CON0             (*(volatile unsigned int *)(SCU_BASE_ADDRESS + 0x100))
#define SCU_EICR1                   (*(volatile unsigned int *)(SCU_BASE_ADDRESS + 0x214))
#define SCU_IGCR0                   (*(volatile unsigned int *)(SCU_BASE_ADDRESS + 0x22C))

#define SRC_BASE_ADDRESS        (0xF0038000)
#define SRC_STM0_SR0            (*(volatile unsigned int *)(SRC_BASE_ADDRESS + 0x490))
#define SRC_SCU_ERU0            (*(volatile unsigned int *)(SRC_BASE_ADDRESS + 0xCD4))
#define SRC_SCU_ERU1            (*(volatile unsigned int *)(SRC_BASE_ADDRESS + 0xCD8))
    // 0xCD4 + 4m   /m = eru num

#define EXIS0                   4
#define FEN0                    8
#define EIEN0                   11
#define INP0                    12
#define IGP0                    14

#define EXIS1                   20
#define FEN1                    24
#define EIEN1                   27
#define INP1                    28
#define IGP1                    30

#define SRE                     10
#define TOS                     11
#define SRPN                    (0)

/* Field bit positions of SCU Registers */
#define LCK                         1
#define ENDINIT                     0



// Timer Module (STM) registers
#define STM0_BASE_ADDRESS       (0xF0000000)
#define STM0_TIM0               (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x10))
#define STM0_CMP0               (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x30))
#define STM0_CMCON              (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x38))
#define STM0_ICR                (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x3C))
#define STM0_ISCR               (*(volatile unsigned int *)(STM0_BASE_ADDRESS + 0x40))

#define CMP0EN                  (0)
#define CMP0OS                  (2)
#define CMP0IRR                 (0)
#define MSIZE0                  (0)
#define MSTART0                 (8)

#define STM_FREQENCY_HZ         (100000000UL)
#define STM0_TICKS_1SEC         (STM_FREQENCY_HZ)
#define STM0_TICKS_HALF_SEC     (STM_FREQENCY_HZ / 2)


/*
    PWM
*/
// Generic Timer Module (GTM) registers
#define GTM_BASE_ADDRESS        (0xF0100000)
#define GTM_CLC                 (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x9FD00))
#define GTM_TOUTSEL6            (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x9FD48))

#define DISS                    1
#define DISR                    0
#define SEL7                    14

// Generic Timer Module (GTM) - Clock Management Unit (CMU) registers
#define GTM_CMU_CLK_EN          (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x00300))
#define GTM_CMU_FXCLK_CTRL      (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x00344))

#define EN_FXCLK                22
#define FXCLK_SEL               0

// Generic Timer Module (GTM) - Timer Output Module (TOM) registers - TOM0, Channel 1 - Led PWM
#define GTM_TOM0_TGC0_GLB_CTRL      (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08030))
#define GTM_TOM0_TGC0_ENDIS_CTRL    (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08070))
#define GTM_TOM0_TGC0_OUTEN_CTRL    (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08078))
#define GTM_TOM0_TGC0_FUPD_CTRL     (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08038))

#define GTM_TOM0_CH1_CTRL           (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08040))
#define GTM_TOM0_CH1_SR0            (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08044))
#define GTM_TOM0_CH1_SR1            (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08048))

#define UPEN_CTRL1              18
#define ENDIS_CTRL1             2
#define OUTEN_CTRL1             2
#define FUPD_CTRL1              2
#define RSTCN0_CH1              18

// Generic Timer Module (GTM) - Timer Output Module (TOM) registers - TOM0, Channel 11 - buzzer PWM
#define GTM_TOM0_TGC1_GLB_CTRL      (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08230))
#define GTM_TOM0_TGC1_ENDIS_CTRL    (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08270))
#define GTM_TOM0_TGC1_OUTEN_CTRL    (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08278))
#define GTM_TOM0_TGC1_FUPD_CTRL     (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x08238))

// TOM0 Channel 11 레지스터 주소
#define GTM_TOM0_CH11_CTRL          (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x082C0))
#define GTM_TOM0_CH11_SR0           (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x082C4))
#define GTM_TOM0_CH11_SR1           (*(volatile unsigned int *)(GTM_BASE_ADDRESS + 0x082C8))

#define UPEN_CTRL11                 22
#define ENDIS_CTRL11                6   
#define OUTEN_CTRL11                6   
#define FUPD_CTRL11                 6   
#define RSTCN0_CH11                 22

#define HOST_TRIG               0
#define CLK_SRC_SR              12
#define SL                      11

/*
 * Priority: 0 ~ 15, 0 is the highest
*/
#define SW1_PRIORITY            0xF
#define SW2_PRIORITY            0xE
#define STM0_ISR_PRIORITY       (10)    // timer interrupt priority

/*
 * Position Thresholds for Potentiometer
 * adc: 0 ~ 4095
 */
#define POT_CENTER_MIN          1800
#define POT_CENTER_MAX          2300
#define POT_LEFT_MAX            1000
#define POT_RIGHT_MIN           3100
#define POT_MIN                 0
#define POT_MAX                 4095


/* ============================================================
 * Function Prototypes
 * ============================================================ */
void init_LED(void);
void init_Switch(void);
void init_RGBLED(void);
void init_Buzzer(void);

void init_ERU(void);
void init_Timer_1sec_Interrupt(void);
void init_VADC(void);
void init_GTM_TOM0_PWM(void);

void VADC_start_conversion(void);
unsigned int VADC_read_result(void);

IfxCpu_syncEvent cpuSyncEvent = 0;

volatile unsigned int g_stm0_sec_count = 0;
volatile bool g_sw1_flag = false;
volatile bool g_sw2_flag = false;

/*
 * Interrupt Functions
* ============================================================ */
__interrupt(SW1_PRIORITY)   __vector_table(0)
void ISR0(void){
    g_sw1_flag = !g_sw1_flag;

    if (g_sw1_flag == false)
        PORT10_OMR |= ((0x1 << PCL2) | (0x0 << PS2));   // red off
}

__interrupt(SW2_PRIORITY)   __vector_table(0)
void ISR1(void){
    g_sw2_flag = !g_sw2_flag;

    if (g_sw2_flag == false)
        PORT10_OMR |= ((0x1 << PCL1) | (0x0 << PS1));   // blue off
}

__interrupt(STM0_ISR_PRIORITY)   __vector_table(0)
void Stm0_Compare0_Isr(void) {
    STM0_ISCR |= ((0x1) << CMP0IRR);                // clear compare 0 interrupt request flag

    STM0_CMP0 += (unsigned int)STM0_TICKS_HALF_SEC;  // set compare 0 to trigger next interrupt after 0.5 second
    
    g_stm0_sec_count++;                             // increment the seconds counter

    if (g_sw1_flag) {
        PORT10_OMR |= ((0x1 << PCL2) | (0x1 << PS2));   // blue toggle
        // buzzer toggle?
    }

    if (g_sw2_flag) {
        PORT10_OMR |= ((0x1 << PCL1) | (0x1 << PS1));   // red toggle
        // buzzer toggle?
    }    
}


/* ============================================================
 * Main Function
 * ============================================================ */

void core0_main(void)
{
    typedef enum { 
        STATE_UNKNOWN = 0, 
        STATE_CENTER, 
        STATE_LEFT, 
        STATE_RIGHT 
    } PotState;

    PotState current_state = STATE_UNKNOWN;

    unsigned int adc_result = 0;

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    // init
    init_LED();
    init_Switch();
    init_Buzzer();

    init_ERU();
    init_VADC();

    // init interrupt
   
    init_Timer_1sec_Interrupt();

    // init_RGBLED();
    // init_GTM_TOM0_PWM();
    
    while(1)
    {
        VADC_start_conversion();
        adc_result = VADC_read_result();

        // Determine the current state based on the ADC result
        if (current_state == STATE_UNKNOWN) {
            if (adc_result <= POT_LEFT_MAX)
                current_state = STATE_LEFT;
            else if (adc_result >= POT_RIGHT_MIN)
                current_state = STATE_RIGHT;
            else if (adc_result >= POT_CENTER_MIN && adc_result <= POT_CENTER_MAX)
                current_state = STATE_CENTER;
        }
        else {  // current_state is known
            switch (current_state) {

                // left -> center(right)
                case STATE_LEFT:
                    if (adc_result >= POT_CENTER_MIN && adc_result <= POT_CENTER_MAX) {
                        
                        // off blue led
                        g_sw1_flag = false;
                        PORT10_OMR |= ((0x1 << PCL1) | (0x0 << PS1));

                        current_state = STATE_CENTER;
                    }
                    
                    break;

                case STATE_CENTER:
                    if (adc_result <= POT_LEFT_MAX) {
                        // center -> left
                        if (g_sw2_flag) {   
                            // opposite direction, buzzer on
                            // GTM_TOM0_CH11_SR1 
                        }
                        current_state = STATE_LEFT;
                    }
                    else if (adc_result >= POT_RIGHT_MIN) {
                        // center -> right
                        if (g_sw1_flag) {
                            // opposite direction, buzzer on
                            // GTM_TOM0_CH11_SR1
                        }
                        current_state = STATE_RIGHT;
                    }
                    break;
                
                // right -> center(left)
                case STATE_RIGHT:
                    if (adc_result >= POT_CENTER_MIN && adc_result <= POT_CENTER_MAX) {
                        
                        // off red led
                        g_sw2_flag = false;
                        PORT10_OMR |= ((0x1 << PCL2) | (0x0 << PS2));
                        
                        current_state = STATE_CENTER;
                    }
                    break;

                default:
                    current_state = STATE_UNKNOWN;  // Reset to unknown state
                    break;
            }
        }
    }
}

/** 
 * LED Initialization
 * ============================================================ */
void init_LED(void) {
    // Initialize LED pins as output
    PORT10_IOCR0 &= ~((0x1F) << PC1);   // reset pc1 in port 10 IOCR0 register
    PORT10_IOCR0 |= ((0x10) << PC1);    // set pc1 to push-pull mode in port10 IOCR register

    PORT10_IOCR0 &= ~((0x1F) << PC2);   // reset pc2 in port 10 IOCR0 register
    PORT10_IOCR0 |= ((0x10) << PC2);    // set pc2 to push-pull mode in port10 IOCR register
}

/**
 * Switch Initialization
 * ============================================================ */
void init_Switch(void) {
    // Initialize Switch pins as input
    PORT2_IOCR0 &= ~((0x1F) << PC0);   // reset pc1 in port 2 IOCR0 register
    PORT2_IOCR0 |= ((0x02) << PC0);    // set pc1 to input mode in port2 IOCR register

    PORT2_IOCR0 &= ~((0x1F) << PC1);   // reset pc2 in port 2 IOCR0 register
    PORT2_IOCR0 |= ((0x02) << PC1);    // set pc2 to input mode in port2 IOCR register
}

/**
 * Buzzer Initialization
 * ============================================================ */
void init_Buzzer(void) {
    // Initialize Buzzer pins as output
    PORT2_IOCR0 &= ~((0x1F) << PC3);   // reset pc3 in port 10 IOCR0 register
    PORT2_IOCR0 |= ((0x11) << PC3);    // set pc3 to push-pull mode in port10 IOCR register
}

/*
 * ERU Initialization
 * ============================================================ */
void init_ERU(void) {
    // Initialize ERU pins
    //ERU; External Request Unit  setting

    //// switch 1 - D2 - P2.0
    SCU_EICR1 &= ~(0x7 << EXIS1);           // clear input source selection field
    SCU_EICR1 |= (0x2 << EXIS1);            // select P02.0 as ERU input source // 0x2 represents the third input

    SCU_EICR1 |= (0x1 << FEN1);             // Enable falling-edge detection
    SCU_EICR1 |= (0x1 << EIEN1);            // Enable event generation for input channel

    SCU_EICR1 &= ~(0x7 << INP1);            // reset input source selection field
    SCU_EICR1 |= (0x1 << INP1);             // route event to output channel 1

    SCU_IGCR0 &= ~(0x3 << IGP1);            // clear gating config for output channel 0
    SCU_IGCR0 |= (0x1 << IGP1);             // activate interrupt output when trigger occurs

    // SRC
    SRC_SCU_ERU1 &= ~(0xFF);                // clear service request prioirty field
    SRC_SCU_ERU1 |= (SW1_PRIORITY);         // set interrupr priority to 0x0E

    SRC_SCU_ERU1 |= (1 << SRE);             // enable service request generation
    SRC_SCU_ERU1 &= ~(0x3 << TOS);          // route service request to CPU0

    /////////////
    //switch 2 - D3 - P2.1
    SCU_EICR1 &= ~(0x7 << EXIS0);           // clear input source selection field
    SCU_EICR1 |= (0x1 << EXIS0);            // select P02.1 as ERU input source

    SCU_EICR1 |= (0x1 << FEN0);             // Enable falling-edge detection
    SCU_EICR1 |= (0x1 << EIEN0);            // Enable event generation for input channel

    SCU_EICR1 &= ~(0x7 << INP0);            // clear input source selection field

    SCU_IGCR0 &= ~(0x3 << IGP0);            // clear gating config for output channel 0
    SCU_IGCR0 |= (0x1 << IGP0);             // activate interrupt output when trigger occurs

    // SRC; Service Request Control setting
    SRC_SCU_ERU0 &= ~(0xFF);                // clear service request prioirty field
    SRC_SCU_ERU0 |= (SW2_PRIORITY);         // set interrupr priority to 0x0F

    SRC_SCU_ERU0 |= (1 << SRE);             // enable service request generation
    SRC_SCU_ERU0 &= ~(0x3 << TOS);          // route service request to CPU0
}

/* 
 * VADC Initialization
 * ============================================================ */
void init_VADC(void) {
    // Clear ENDINIT protection to allow modification of protected registers

    // Password Access to unlock CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 = 
        ((SCU_WDTCPU0CON0 ^ 0xFC) & ~(1 << LCK))
        | (1 << ENDINIT);

    while ((SCU_WDTCPU0CON0 & (1 << LCK)) != 0);      // wait until to unlock CPU0 WDT Control Register 0

    // Modify Access to clear the ENDINIT bit in CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 =
        ((SCU_WDTCPU0CON0 ^ 0xFC) | (1 << LCK))
        & ~(1 << ENDINIT);

    while ((SCU_WDTCPU0CON0 & (1 << LCK)) == 0);      // wait until to clear the ENDINIT bit in CPU0 WDT Control Register 0


    VADC_CLC &= ~(1u << DISR);                          // Enable VADC module clock by clearing the DISS bit in the VADC_CLC register

    // Password Access to unlock CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 =
        ((SCU_WDTCPU0CON0 ^ 0xFC) & ~(1 << LCK))
        | (1 << ENDINIT);

    while ((SCU_WDTCPU0CON0 & (1u << LCK)) != 0);      // wait until to unlock CPU0 WDT Control Register 0

    // Modify Access to set the ENDINIT bit in CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 =
        ((SCU_WDTCPU0CON0 ^ 0xFC) | (1 << LCK))
        | (1 << ENDINIT);

    while ((SCU_WDTCPU0CON0 & (1 << LCK)) == 0);

    // Wait until the DISS bit in the VADC_CLC register is cleared, indicating that the VADC module is enabled
    while ((VADC_CLC & (1 << DISS)) != 0);


    // Configure Group 4 Arbitration to use the highest priority for Request Source 0, wait-for-start conversion mode, and enable Arbitration Source Input 0

    /* Set Request Source 0 to highest priority */
    VADC_G4ARBPR |= ((0x3u) << PRIO0);

    /* Select wait-for-start conversion mode */
    VADC_G4ARBPR &= ~(1u << CSM0);

    /* Enable Arbitration Source Input 0 */
    VADC_G4ARBPR |= (1u << ASEN0);


    /* --------------------------------------------------------
     * Configure Queue
     * -------------------------------------------------------- */

    /* Clear Queue gate-control field */
    VADC_G4QMR0 &= ~((0x3u) << ENGT);

    /* Enable Queue conversion requests */
    VADC_G4QMR0 |= ((0x1u) << ENGT);

    /* Remove all existing Queue entries */
    VADC_G4QMR0 |= (1u << FLUSH);


    /* --------------------------------------------------------
     * Configure converter
     * -------------------------------------------------------- */

    /* Set Group 4 converter to normal operation */
    VADC_G4ARBCFG |= ((0x3u) << ANONC);

    /* Select 12-bit standard conversion mode */
    VADC_G4ICLASS0 &= ~((0x7u) << CMS);


    /* --------------------------------------------------------
     * Configure Channel 7
     * -------------------------------------------------------- */

    /* Store Channel 7 result in right-aligned format */
    VADC_G4CHCTR7 |= (1u << RESPOS);

    /* Clear result-register selection field */
    VADC_G4CHCTR7 &= ~((0xFu) << RESREG);

    /* Store Channel 7 result in Group Result Register 1 */
    VADC_G4CHCTR7 |= (1u << RESREG);

    /* Select Group-specific Input Class 0 */
    VADC_G4CHCTR7 &= ~((0x3u) << ICLSEL);
}

/* 
 * Start Single VADC Conversion
 * ============================================================ */
void VADC_start_conversion(void)
{
    /* Reset queue channel selection bits */
    VADC_G4QINR0 &= ~0x1Fu;

    /* Select Group 4 Channel 7 */
    VADC_G4QINR0 |= 0x07u;

    /* Configure queue entry for a single conversion */
    VADC_G4QINR0 &= ~(1u << RF);

    /* Software trigger */
    VADC_G4QMR0 |= (1u << TREV);
}


/* 
 * Read VADC Result
 * ============================================================ */
unsigned int VADC_read_result(void)
{
    unsigned int result;

    /* Wait until result-valid flag is set */
    while ((VADC_G4RES1 & (1u << VF)) == 0u)
    {
    }

    /* Read 12-bit ADC conversion result */
    result = VADC_G4RES1 & (0xFFFu << RESULT);

    return result;
}

/* 
 * Timer Initialization
 * ============================================================ */

void init_Timer_1sec_Interrupt(void) {
    unsigned int currentTime;

    STM0_ICR &= ~((0x1) << CMP0EN);                 // disable compare 0 interrupt

    SRC_STM0_SR0 &= ~((0x1) << SRE);                // disable service request generation

    STM0_CMCON &= ~((0x1) << MSTART0);              // set compare 0 to start counting from STM0_TIM0
    STM0_CMCON |= ((0x1F) << MSIZE0);               // set compare 0 to 32-bit mode

    STM0_ICR &= ~((0x1) << CMP0OS);                 // set compare 0 to one-shot mode

    STM0_ISCR |= ((0x1) << CMP0IRR);                // clear compare 0 interrupt request flag

    currentTime = STM0_TIM0;                        // get current STM0 time

    // STM0_CMP0 = currentTime + (unsigned int)STM0_TICKS_1SEC;
    STM0_CMP0 = currentTime + (unsigned int)STM0_TICKS_HALF_SEC;

    SRC_STM0_SR0 &= ~(STM0_ISR_PRIORITY << SRPN);   // clear service request priority field
    SRC_STM0_SR0 |= (STM0_ISR_PRIORITY << SRPN);    // set service request priority to 

    SRC_STM0_SR0 &= ~(0x3 << TOS);                  // route service request to CPU0 
    SRC_STM0_SR0 |= ((0x1) << SRE);                 // enable service request generation

    STM0_ICR |= ((0x1) << CMP0EN);                  // enable compare 0 interrupt
}

/* 
 * PWM Initialization - GTM TOM0, Channel 11
 * ============================================================ */
void init_GTM_TOM0_PWM(void) {
    // Password Access to unlock CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 = ((SCU_WDTCPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);    // clear LCK bit and set ENDINIT bit
    while ((SCU_WDTCPU0CON0 & (1 << LCK)) != 0);    // wait until to unlock CPU0 WDT Control Register 0
    
    // Modify Access to clear the ENDINIT bit in CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 = ((SCU_WDTCPU0CON0 ^ 0xFC) | (1 << LCK)) & ~(1 << ENDINIT);        // set LCK bit and clear ENDINIT bit
    while ((SCU_WDTCPU0CON0 & (1 << LCK)) == 0);    // wait until to clear the ENDINIT bit in CPU0 WDT Control Register 0

    // Enable GTM module
    GTM_CLC &= ~(1 << DISR);                        // clear DISS bit to enable GTM module

    // Password Access to unlock CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 = ((SCU_WDTCPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);    // clear LCK bit and set ENDINIT bit
    while ((SCU_WDTCPU0CON0 & (1 << LCK)) != 0);    // wait until to unlock CPU0 WDT Control Register 0

    // Modify Access to set the ENDINIT bit in CPU0 WDT Control Register 0
    SCU_WDTCPU0CON0 = ((SCU_WDTCPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);     // set LCK bit and set ENDINIT bit
    while ((SCU_WDTCPU0CON0 & (1 << LCK)) == 0);    // wait until to set the ENDINIT bit in CPU0 WDT Control Register 0

    while ((GTM_CLC & (1 << DISS)) != 0);           // wait until GTM module is enabled

    // GTM Fixed Clock (FXCLK) Configuration
    GTM_CMU_FXCLK_CTRL &= ~((0xF) << FXCLK_SEL);    // Input clock of CMU_FXCLK     // clear FXCLK_SEL bits to select FXCLK source as PLL1
    GTM_CMU_CLK_EN |= ((0x2) << EN_FXCLK);          // Enable all CMU_FXCLK         // set EN_FXCLK bit to enable FXCLK

    /////////////////////////////////////////////////////////// Buzzer PWM
    // Shadow register 및 Force Update 허용
    GTM_TOM0_TGC1_GLB_CTRL |= ((0x2) << UPEN_CTRL11);   
    GTM_TOM0_TGC1_FUPD_CTRL |= ((0x2) << FUPD_CTRL11);   
    GTM_TOM0_TGC1_FUPD_CTRL |= ((0x2) << RSTCN0_CH11);   

    // CH11 활성화 및 출력 활성화 (0x2 = Enable)
    GTM_TOM0_TGC1_ENDIS_CTRL &= ~((0x3) << ENDIS_CTRL11);
    GTM_TOM0_TGC1_ENDIS_CTRL |= ((0x2) << ENDIS_CTRL11); 
    GTM_TOM0_TGC1_OUTEN_CTRL &= ~((0x3) << OUTEN_CTRL11);
    GTM_TOM0_TGC1_OUTEN_CTRL |= ((0x2) << OUTEN_CTRL11); 

    // CH11 Control 설정 (Active High, FXCLK0 사용)
    GTM_TOM0_CH11_CTRL |= (1 << SL);                 
    GTM_TOM0_CH11_CTRL &= ~((0x7) << CLK_SRC_SR);    
    GTM_TOM0_CH11_CTRL |= ((0x1) << CLK_SRC_SR);     

    // 부저 PWM 주기(음정) 및 듀티비(볼륨) 초기 설정 (약 1kHz)
    GTM_TOM0_CH11_SR0 = 6250;       // 주기 설정 (약 1kHz)                    
    GTM_TOM0_CH11_SR1 = 0;          // 듀티비 설정 (0% 듀티비, 부저 OFF)

    GTM_TOM0_TGC1_GLB_CTRL |= ((0x1) << HOST_TRIG);
}